export const data = [
  {
    businesses: [
      {
        id: "NNMvUp-r7sQt7Q2l-kO9wA",
        alias: "the-breakfast-klub-houston-2",
        name: "The Breakfast Klub",
        image_url:
          "https://s3-media4.fl.yelpcdn.com/bphoto/g8NDOIsnM-fV5w8VMwv1tQ/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/the-breakfast-klub-houston-2?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 5721,
        categories: [
          {
            alias: "breakfast_brunch",
            title: "Breakfast & Brunch",
          },
          {
            alias: "southern",
            title: "Southern",
          },
          {
            alias: "tradamerican",
            title: "American (Traditional)",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.73843,
          longitude: -95.38048,
        },
        transactions: ["pickup", "delivery"],
        price: "$$",
        location: {
          address1: "3711 Travis St",
          address2: "",
          address3: "",
          city: "Houston",
          zip_code: "77002",
          country: "US",
          state: "TX",
          display_address: ["3711 Travis St", "Houston, TX 77002"],
        },
        phone: "+17135288561",
        display_phone: "(713) 528-8561",
        distance: 8151.768817800469,
      },
      {
        id: "E8Kfjp5xQYj-D2fx_YBC7g",
        alias: "uchi-houston",
        name: "Uchi",
        image_url:
          "https://s3-media4.fl.yelpcdn.com/bphoto/Y50kR_F6YcUik0vTPbzDig/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/uchi-houston?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 2362,
        categories: [
          {
            alias: "sushi",
            title: "Sushi Bars",
          },
          {
            alias: "japanese",
            title: "Japanese",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.744911,
          longitude: -95.3907523,
        },
        transactions: ["delivery"],
        price: "$$$$",
        location: {
          address1: "904 Westheimer Rd",
          address2: "Ste A",
          address3: "",
          city: "Houston",
          zip_code: "77006",
          country: "US",
          state: "TX",
          display_address: ["904 Westheimer Rd", "Ste A", "Houston, TX 77006"],
        },
        phone: "+17135224808",
        display_phone: "(713) 522-4808",
        distance: 6932.99834835273,
      },
      {
        id: "MtrXTHsxOCw0iCtOlPhrGQ",
        alias: "jinya-ramen-bar-houston-houston",
        name: "JINYA Ramen Bar - Houston",
        image_url:
          "https://s3-media2.fl.yelpcdn.com/bphoto/QbDb4ufn9COGfbok5ftblw/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/jinya-ramen-bar-houston-houston?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 3423,
        categories: [
          {
            alias: "ramen",
            title: "Ramen",
          },
          {
            alias: "cocktailbars",
            title: "Cocktail Bars",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.742717,
          longitude: -95.379758,
        },
        transactions: ["pickup", "delivery"],
        price: "$$",
        location: {
          address1: "3201 Louisiana St",
          address2: "Ste 105",
          address3: "",
          city: "Houston",
          zip_code: "77006",
          country: "US",
          state: "TX",
          display_address: [
            "3201 Louisiana St",
            "Ste 105",
            "Houston, TX 77006",
          ],
        },
        phone: "+18329258596",
        display_phone: "(832) 925-8596",
        distance: 8026.715365453276,
      },
      {
        id: "bRA-zzvte71rq5x45J7-zQ",
        alias: "taste-of-texas-houston",
        name: "Taste of Texas",
        image_url:
          "https://s3-media1.fl.yelpcdn.com/bphoto/MAvfDxtgSQaUBCJgnQpfAA/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/taste-of-texas-houston?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 2932,
        categories: [
          {
            alias: "steak",
            title: "Steakhouses",
          },
          {
            alias: "wine_bars",
            title: "Wine Bars",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.782831,
          longitude: -95.556904,
        },
        transactions: ["pickup", "restaurant_reservation", "delivery"],
        price: "$$$",
        location: {
          address1: "10505 Katy Fwy",
          address2: "",
          address3: "",
          city: "Houston",
          zip_code: "77024",
          country: "US",
          state: "TX",
          display_address: ["10505 Katy Fwy", "Houston, TX 77024"],
        },
        phone: "+17139326901",
        display_phone: "(713) 932-6901",
        distance: 9919.848131650146,
      },
      {
        id: "237MSviehmCzD_wwKg4-zA",
        alias: "bosscat-kitchen-and-libations-houston",
        name: "Bosscat Kitchen & Libations",
        image_url:
          "https://s3-media4.fl.yelpcdn.com/bphoto/CUsonAxau5HCqy3QWJVRRw/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/bosscat-kitchen-and-libations-houston?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 2548,
        categories: [
          {
            alias: "newamerican",
            title: "American (New)",
          },
          {
            alias: "whiskeybars",
            title: "Whiskey Bars",
          },
          {
            alias: "breakfast_brunch",
            title: "Breakfast & Brunch",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.7418,
          longitude: -95.450518,
        },
        transactions: ["pickup", "delivery"],
        price: "$$",
        location: {
          address1: "4310 Westheimer Rd",
          address2: "Ste 150",
          address3: null,
          city: "Houston",
          zip_code: "77027",
          country: "US",
          state: "TX",
          display_address: [
            "4310 Westheimer Rd",
            "Ste 150",
            "Houston, TX 77027",
          ],
        },
        phone: "+12815011187",
        display_phone: "(281) 501-1187",
        distance: 3525.102511536737,
      },
      {
        id: "Y-MMPpw4HSaKPp5C1of9fA",
        alias: "chama-gaúcha-brazilian-steakhouse-houston-3",
        name: "Chama Gaúcha Brazilian Steakhouse",
        image_url:
          "https://s3-media3.fl.yelpcdn.com/bphoto/yg4Mi686Jvbpk3xMQS3JQA/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/chama-ga%C3%BAcha-brazilian-steakhouse-houston-3?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 1764,
        categories: [
          {
            alias: "brazilian",
            title: "Brazilian",
          },
          {
            alias: "steak",
            title: "Steakhouses",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.7376852,
          longitude: -95.4831252,
        },
        transactions: ["delivery"],
        price: "$$$",
        location: {
          address1: "5865 Westheimer Rd",
          address2: "",
          address3: "",
          city: "Houston",
          zip_code: "77057",
          country: "US",
          state: "TX",
          display_address: ["5865 Westheimer Rd", "Houston, TX 77057"],
        },
        phone: "+17132449500",
        display_phone: "(713) 244-9500",
        distance: 4856.025408875204,
      },
      {
        id: "NeTU3xFecz5vIeVWmd8LOw",
        alias: "dish-society-houston",
        name: "Dish Society",
        image_url:
          "https://s3-media2.fl.yelpcdn.com/bphoto/ANr_lxb1TQe_fjKIWrDhEw/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/dish-society-houston?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 2612,
        categories: [
          {
            alias: "breakfast_brunch",
            title: "Breakfast & Brunch",
          },
          {
            alias: "newamerican",
            title: "American (New)",
          },
          {
            alias: "southern",
            title: "Southern",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.75051,
          longitude: -95.47869,
        },
        transactions: ["pickup", "delivery"],
        price: "$$",
        location: {
          address1: "5740 San Felipe St",
          address2: "Ste 100",
          address3: "",
          city: "Houston",
          zip_code: "77057",
          country: "US",
          state: "TX",
          display_address: [
            "5740 San Felipe St",
            "Ste 100",
            "Houston, TX 77057",
          ],
        },
        phone: "+18325381060",
        display_phone: "(832) 538-1060",
        distance: 3433.3312559865376,
      },
      {
        id: "RoU8KznQMrRFcIjYVtdZMw",
        alias: "the-pit-room-houston",
        name: "The Pit Room",
        image_url:
          "https://s3-media3.fl.yelpcdn.com/bphoto/KkligACrcO8g-9bn5-O02w/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/the-pit-room-houston?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 2605,
        categories: [
          {
            alias: "bbq",
            title: "Barbeque",
          },
          {
            alias: "southern",
            title: "Southern",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.7342352703345,
          longitude: -95.3939679771603,
        },
        transactions: ["delivery"],
        price: "$$",
        location: {
          address1: "1201 Richmond Ave",
          address2: "",
          address3: "",
          city: "Houston",
          zip_code: "77006",
          country: "US",
          state: "TX",
          display_address: ["1201 Richmond Ave", "Houston, TX 77006"],
        },
        phone: "+12818881929",
        display_phone: "(281) 888-1929",
        distance: 7295.941195950041,
      },
      {
        id: "VQZF4hu7faCkUaJ9RDRpeQ",
        alias: "local-foods-houston",
        name: "Local Foods",
        image_url:
          "https://s3-media1.fl.yelpcdn.com/bphoto/2Qr_peyl2qy3APwTzKUokw/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/local-foods-houston?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 1765,
        categories: [
          {
            alias: "sandwiches",
            title: "Sandwiches",
          },
          {
            alias: "salad",
            title: "Salad",
          },
          {
            alias: "seafood",
            title: "Seafood",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.7195096809181,
          longitude: -95.4164240674591,
        },
        transactions: ["delivery"],
        price: "$$",
        location: {
          address1: "2424 Dunstan Rd",
          address2: "",
          address3: "",
          city: "Houston",
          zip_code: "77005",
          country: "US",
          state: "TX",
          display_address: ["2424 Dunstan Rd", "Houston, TX 77005"],
        },
        phone: "+17135217800",
        display_phone: "(713) 521-7800",
        distance: 7028.911254411013,
      },
      {
        id: "iGMTbYr2FTFHc6vEIn51_Q",
        alias: "steak-48-houston-2",
        name: "Steak 48",
        image_url:
          "https://s3-media2.fl.yelpcdn.com/bphoto/wY7iVDM1x6b02z2wtn-NaA/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/steak-48-houston-2?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 1667,
        categories: [
          {
            alias: "steak",
            title: "Steakhouses",
          },
          {
            alias: "seafood",
            title: "Seafood",
          },
          {
            alias: "bars",
            title: "Bars",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.74178728489348,
          longitude: -95.45451410233659,
        },
        transactions: ["delivery"],
        price: "$$$$",
        location: {
          address1: "4444 Westheimer Rd",
          address2: "",
          address3: "",
          city: "Houston",
          zip_code: "77027",
          country: "US",
          state: "TX",
          display_address: ["4444 Westheimer Rd", "Houston, TX 77027"],
        },
        phone: "+17133227448",
        display_phone: "(713) 322-7448",
        distance: 3501.3714621910513,
      },
      {
        id: "sLrHO2ct7qsJERWYXrR1pg",
        alias: "kata-robata-houston",
        name: "Kata Robata",
        image_url:
          "https://s3-media2.fl.yelpcdn.com/bphoto/VH9BXrb5xJlR9z7iOOCWrA/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/kata-robata-houston?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 1963,
        categories: [
          {
            alias: "sushi",
            title: "Sushi Bars",
          },
          {
            alias: "japanese",
            title: "Japanese",
          },
          {
            alias: "asianfusion",
            title: "Asian Fusion",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.7335727255874,
          longitude: -95.4194910185242,
        },
        transactions: ["pickup", "delivery"],
        price: "$$$",
        location: {
          address1: "3600 Kirby Dr",
          address2: "Ste H",
          address3: "",
          city: "Houston",
          zip_code: "77098",
          country: "US",
          state: "TX",
          display_address: ["3600 Kirby Dr", "Ste H", "Houston, TX 77098"],
        },
        phone: "+17135268858",
        display_phone: "(713) 526-8858",
        distance: 5572.292148316103,
      },
      {
        id: "x4WealiPVG-tzwzhe7nvpw",
        alias: "north-italia-houston",
        name: "North Italia",
        image_url:
          "https://s3-media4.fl.yelpcdn.com/bphoto/TeH1zQEHlKbTclf8z0R3PA/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/north-italia-houston?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 2135,
        categories: [
          {
            alias: "pizza",
            title: "Pizza",
          },
          {
            alias: "italian",
            title: "Italian",
          },
          {
            alias: "cocktailbars",
            title: "Cocktail Bars",
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 29.7485868638914,
          longitude: -95.4620253208921,
        },
        transactions: ["delivery"],
        price: "$$",
        location: {
          address1: "1700 Post Oak Blvd",
          address2: "Ste 190",
          address3: "",
          city: "Houston",
          zip_code: "77056",
          country: "US",
          state: "TX",
          display_address: [
            "1700 Post Oak Blvd",
            "Ste 190",
            "Houston, TX 77056",
          ],
        },
        phone: "+12816054030",
        display_phone: "(281) 605-4030",
        distance: 2834.558404109229,
      },
      {
        id: "fIs1oqMQ8V1kC6175N1x-g",
        alias: "roostar-vietnamese-grill-houston-2",
        name: "Roostar Vietnamese Grill",
        image_url:
          "https://s3-media1.fl.yelpcdn.com/bphoto/to814A6oCyobmgeVnk8gXQ/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/roostar-vietnamese-grill-houston-2?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 1601,
        categories: [
          {
            alias: "vietnamese",
            title: "Vietnamese",
          },
          {
            alias: "sandwiches",
            title: "Sandwiches",
          },
          {
            alias: "vegetarian",
            title: "Vegetarian",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.7956689067855,
          longitude: -95.5451280889549,
        },
        transactions: ["pickup", "delivery"],
        price: "$$",
        location: {
          address1: "1411 Gessner Rd",
          address2: "Ste I",
          address3: "",
          city: "Houston",
          zip_code: "77080",
          country: "US",
          state: "TX",
          display_address: ["1411 Gessner Rd", "Ste I", "Houston, TX 77080"],
        },
        phone: "+18326498955",
        display_phone: "(832) 649-8955",
        distance: 9074.037070662527,
      },
      {
        id: "AAf5Mq-xpME2bkB1Z1auaQ",
        alias: "common-bond-bistro-and-bakery-montrose-houston",
        name: "Common Bond Bistro & Bakery - Montrose",
        image_url:
          "https://s3-media2.fl.yelpcdn.com/bphoto/hYGWp569uc5KxAQo5-w9CQ/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/common-bond-bistro-and-bakery-montrose-houston?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 2376,
        categories: [
          {
            alias: "cafes",
            title: "Cafes",
          },
          {
            alias: "bakeries",
            title: "Bakeries",
          },
          {
            alias: "breakfast_brunch",
            title: "Breakfast & Brunch",
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 29.7428969,
          longitude: -95.4023708,
        },
        transactions: ["pickup", "delivery"],
        price: "$$",
        location: {
          address1: "1706 Westheimer Rd",
          address2: "",
          address3: "",
          city: "Houston",
          zip_code: "77098",
          country: "US",
          state: "TX",
          display_address: ["1706 Westheimer Rd", "Houston, TX 77098"],
        },
        phone: "+17135293535",
        display_phone: "(713) 529-3535",
        distance: 6077.732059150616,
      },
      {
        id: "24CtuevOqpbyAaXjrZLq1A",
        alias: "roostar-vietnamese-grill-houston-3",
        name: "Roostar Vietnamese Grill",
        image_url:
          "https://s3-media4.fl.yelpcdn.com/bphoto/n6KtnV7uyhNHiEkFQbqLeQ/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/roostar-vietnamese-grill-houston-3?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 1053,
        categories: [
          {
            alias: "vietnamese",
            title: "Vietnamese",
          },
          {
            alias: "sandwiches",
            title: "Sandwiches",
          },
          {
            alias: "vegetarian",
            title: "Vegetarian",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.7313251,
          longitude: -95.4753633,
        },
        transactions: ["pickup", "delivery"],
        price: "$",
        location: {
          address1: "5551 Richmond Ave",
          address2: null,
          address3: "",
          city: "Houston",
          zip_code: "77056",
          country: "US",
          state: "TX",
          display_address: ["5551 Richmond Ave", "Houston, TX 77056"],
        },
        phone: "+18327673319",
        display_phone: "(832) 767-3319",
        distance: 5069.468625281214,
      },
      {
        id: "kHyVzbt2NvIqxwcDIhqNvg",
        alias: "snooze-an-a-m-eatery-houston-18",
        name: "Snooze, an A.M. Eatery",
        image_url:
          "https://s3-media4.fl.yelpcdn.com/bphoto/rNJ2870JZiu1I1iajBo7dg/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/snooze-an-a-m-eatery-houston-18?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 2482,
        categories: [
          {
            alias: "breakfast_brunch",
            title: "Breakfast & Brunch",
          },
          {
            alias: "tradamerican",
            title: "American (Traditional)",
          },
          {
            alias: "cocktailbars",
            title: "Cocktail Bars",
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 29.743975,
          longitude: -95.390925,
        },
        transactions: ["delivery"],
        price: "$$",
        location: {
          address1: "3217 Montrose Blvd",
          address2: "Ste 100",
          address3: null,
          city: "Houston",
          zip_code: "77006",
          country: "US",
          state: "TX",
          display_address: [
            "3217 Montrose Blvd",
            "Ste 100",
            "Houston, TX 77006",
          ],
        },
        phone: "+17135746655",
        display_phone: "(713) 574-6655",
        distance: 6960.162841725647,
      },
      {
        id: "NG_CTxPXJGCU4detUtUqew",
        alias: "pappas-bros-steakhouse-houston-7",
        name: "Pappas Bros. Steakhouse",
        image_url:
          "https://s3-media3.fl.yelpcdn.com/bphoto/lh5YQy5Za2pMGS25ehs6Jw/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/pappas-bros-steakhouse-houston-7?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 1170,
        categories: [
          {
            alias: "steak",
            title: "Steakhouses",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.737449,
          longitude: -95.481804,
        },
        transactions: ["delivery"],
        price: "$$$$",
        location: {
          address1: "5839 Westheimer Rd",
          address2: "",
          address3: "",
          city: "Houston",
          zip_code: "77057",
          country: "US",
          state: "TX",
          display_address: ["5839 Westheimer Rd", "Houston, TX 77057"],
        },
        phone: "+17137807352",
        display_phone: "(713) 780-7352",
        distance: 4765.481639251265,
      },
      {
        id: "02GjIP_ReWd2GqVu9yFV_Q",
        alias: "luna-pizzeria-houston",
        name: "Luna Pizzeria",
        image_url:
          "https://s3-media3.fl.yelpcdn.com/bphoto/yRSbFhMERnTSwkWHNfJr0A/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/luna-pizzeria-houston?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 1121,
        categories: [
          {
            alias: "pizza",
            title: "Pizza",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.7350980889096,
          longitude: -95.4177527502179,
        },
        transactions: ["delivery"],
        price: "$$",
        location: {
          address1: "3435 Kirby Dr",
          address2: "",
          address3: "",
          city: "Houston",
          zip_code: "77098",
          country: "US",
          state: "TX",
          display_address: ["3435 Kirby Dr", "Houston, TX 77098"],
        },
        phone: "+18327676338",
        display_phone: "(832) 767-6338",
        distance: 5545.3302564655905,
      },
      {
        id: "LYBeb7EJfh8v5JwO6HWeYA",
        alias: "baby-barnabys-houston-5",
        name: "Baby Barnaby's",
        image_url:
          "https://s3-media4.fl.yelpcdn.com/bphoto/n8TgW8wiNF0SgHuKkvVAQA/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/baby-barnabys-houston-5?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 1559,
        categories: [
          {
            alias: "breakfast_brunch",
            title: "Breakfast & Brunch",
          },
          {
            alias: "tradamerican",
            title: "American (Traditional)",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.7482894,
          longitude: -95.38835431177905,
        },
        transactions: ["pickup"],
        price: "$$",
        location: {
          address1: "602 Fairview St",
          address2: "",
          address3: "",
          city: "Houston",
          zip_code: "77006",
          country: "US",
          state: "TX",
          display_address: ["602 Fairview St", "Houston, TX 77006"],
        },
        phone: "+17135224229",
        display_phone: "(713) 522-4229",
        distance: 6982.009709946122,
      },
      {
        id: "I1VlZBW80UL3E3NvahlqXg",
        alias: "oporto-fooding-house-and-wine-houston",
        name: "Oporto Fooding House & Wine",
        image_url:
          "https://s3-media3.fl.yelpcdn.com/bphoto/RnVfaa7hViD50C3J845MCA/o.jpg",
        is_closed: false,
        url: "https://www.yelp.com/biz/oporto-fooding-house-and-wine-houston?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        review_count: 1371,
        categories: [
          {
            alias: "tapasmallplates",
            title: "Tapas/Small Plates",
          },
          {
            alias: "portuguese",
            title: "Portuguese",
          },
          {
            alias: "wine_bars",
            title: "Wine Bars",
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 29.7531663748913,
          longitude: -95.38029690072669,
        },
        transactions: ["pickup", "delivery"],
        price: "$$",
        location: {
          address1: "125 W Gray St",
          address2: "Ste 500",
          address3: "",
          city: "Houston",
          zip_code: "77019",
          country: "US",
          state: "TX",
          display_address: ["125 W Gray St", "Ste 500", "Houston, TX 77019"],
        },
        phone: "+17135280115",
        display_phone: "(713) 528-0115",
        distance: 7523.001137418169,
      },
    ],
    total: 5700,
    region: {
      center: {
        longitude: -95.4547119140625,
        latitude: 29.773275441610096,
      },
    },
  },
];

export const review = [
  {
    reviews: [
      {
        id: "sBR_AO7CQitDxRpi4pkLtw",
        url: "https://www.yelp.com/biz/the-breakfast-klub-houston-2?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&hrid=sBR_AO7CQitDxRpi4pkLtw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        text: "I know Mr. Davis and His wonderful Parents.\nThe food is always fresh and delicious like Family prepared the meals.\nFresh juices with a variety of...",
        rating: 5,
        time_created: "2023-02-21 18:51:25",
        user: {
          id: "ppe3NKXHEtfvnJkiRCsTSA",
          profile_url:
            "https://www.yelp.com/user_details?userid=ppe3NKXHEtfvnJkiRCsTSA",
          image_url:
            "https://s3-media3.fl.yelpcdn.com/photo/6sBs7i4APPj87K2C5fnHLQ/o.jpg",
          name: "Zena P.",
        },
      },
      {
        id: "Naif29aCXiwF9AcvtHvRrA",
        url: "https://www.yelp.com/biz/the-breakfast-klub-houston-2?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&hrid=Naif29aCXiwF9AcvtHvRrA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        text: "I fell in love as soon as I was greeted by a very very nice friendly, and comforting employee, who assisted me by explaining how everything worked in the...",
        rating: 5,
        time_created: "2023-02-21 10:59:19",
        user: {
          id: "pUZrHnleLx4c80NG6DJJOw",
          profile_url:
            "https://www.yelp.com/user_details?userid=pUZrHnleLx4c80NG6DJJOw",
          image_url:
            "https://s3-media2.fl.yelpcdn.com/photo/zLiyWeqpiPODoU3s1WHaPg/o.jpg",
          name: "Rachelle V.",
        },
      },
      {
        id: "4c1dNM790jhp9hO7wOYMSw",
        url: "https://www.yelp.com/biz/the-breakfast-klub-houston-2?adjust_creative=rI9ATiioXqbd4JbSPEn_yg&hrid=4c1dNM790jhp9hO7wOYMSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=rI9ATiioXqbd4JbSPEn_yg",
        text: "Super great ....... Cant wait to go back!!!!!!      The portions are unreal!!!   Catfish breakfast is a must",
        rating: 5,
        time_created: "2023-02-09 17:55:18",
        user: {
          id: "qap3DanQLvcdv_oq-XEGBw",
          profile_url:
            "https://www.yelp.com/user_details?userid=qap3DanQLvcdv_oq-XEGBw",
          image_url: null,
          name: "E B.",
        },
      },
    ],
    total: 5721,
    possible_languages: ["en", "es", "zh", "fr"],
  },
];
